_BASE_: "../Base-RetinaNet.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "/home/ilia/Downloads/model_final_5bd44e.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (11000, 15000)
  MAX_ITER: 20000
  IMS_PER_BATCH: 4
DATASETS:
  TRAIN: ("pig_train",)
  TEST: ("pig_val",)
