_BASE_: "../Base-RetinaNet.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "/home/farmsee/Downloads/model_final_5bd44e.pkl"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
  RETINANET:
      NUM_CLASSES: 6
INPUT:
  RANDOM_FLIP: vertical
SOLVER:
  STEPS: (11000, 15000)
  MAX_ITER: 20000
  IMS_PER_BATCH: 4
  WARMUP_ITERS: 2500
DATASETS:
  TRAIN: ("tag_detection_train",)
  TEST: ("tag_detection_val",)
  DS_NAME: "tag_detection"
  DATA_DIR: "/home/farmsee/_data/_DS/pig_big_coco/100/"
